package cotg.helpers;

public enum ATTACK_TYPES {
	VANQ_ASSAULT, SORC_ASSAULT, HORSE_ASSAULT, DRUID_ASSAULT,
	
	VANQ_SIEGE, SORC_SIEGE, HORSE_SIEGE, DRUID_SIEGE,
	
	VANQ_SEN_SIEGE, SORC_SEN_SIEGE, HORSE_SEN_SIEGE, WS_SEN_SIEGE, DRUID_SEN_SIEGE,
	
	WS_SIEGE,
	
	FAKE, WS,
	
	FAKE_SCOUT, FAKE_SIEGE, FAKE_ASSAULT
}
